DROP DATABASE IF EXISTS populacao_data;
CREATE DATABASE populacao_data;
USE populacao_data;
CREATE TABLE populacao(
	ID_POP INT NOT NULL AUTO_INCREMENT,
    UF CHAR(2) NOT NULL,
    COD_UF INT NOT NULL,
    COD_MUNICIPIO INT NOT NULL,
    NOME_MUNICIPIO VARCHAR(255) NOT NULL,
    POPULACAO INT NOT NULL,
    PRIMARY KEY (ID_POP)
);